
services:
  smartplug-service:
    depends_on:
      - db
    container_name: smartplug-service
    ports:
      - "80:80"
      - "443:443"
    build:
      context: .
      dockerfile: ./Smartplug.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    networks:
      - dev
    links:
      - db
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    restart: always
    networks:
      - dev
    hostname: "db"

networks:
  dev:
    driver: bridge



