services:
  smartplug-service:
    container_name: smartplug-service
    hostname: smartplug
    ports:
      - "5000:8080"
    build:
      context: .
      dockerfile: ./Smartplug.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    networks:
      - app-network
    restart: always

  hangfire-db:
    image: postgres:latest
    container_name: hangfire-db
    hostname: hangfire-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: HangfireDB
    networks:
      - app-network
    restart: always

networks:
  app-network:
    external: true